version: '3.7'

services:
  app:
    container_name: ct-py-sqlite3
    build: "./"
    ports: 
      - 80:5000
    volumes:
      - ./app:/app
    restart: always
    networks:
      - pynet

networks:
  pynet:
    driver: "bridge"

